import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { DEFAULT_ANNOTATION_LABELS, type AnnotationLabel } from "@shared/annotationSets";
import { CheckCircle2, CopyPlus, Pencil, Plus, Star, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type Draft = { id?: number; name: string; description: string; labels: AnnotationLabel[]; isDefault: boolean };
const freshDraft = (): Draft => ({ name: "", description: "", labels: DEFAULT_ANNOTATION_LABELS.map(label => ({ ...label })), isDefault: false });

export default function AnnotationSets() {
  const utils = trpc.useUtils(); const { data: sets = [] } = trpc.annotationSets.list.useQuery(); const [draft, setDraft] = useState<Draft | null>(null);
  const create = trpc.annotationSets.create.useMutation({ onSuccess: () => { utils.annotationSets.list.invalidate(); setDraft(null); toast.success("标注集已创建"); }, onError: error => toast.error(error.message) });
  const update = trpc.annotationSets.update.useMutation({ onSuccess: () => { utils.annotationSets.list.invalidate(); setDraft(null); toast.success("标注集已更新"); }, onError: error => toast.error(error.message) });
  const remove = trpc.annotationSets.remove.useMutation({ onSuccess: () => { utils.annotationSets.list.invalidate(); toast.success("标注集已删除"); }, onError: error => toast.error(error.message) });
  const activeLabels = useMemo(() => draft?.labels.filter(label => label.enabled) ?? [], [draft]);
  const openEdit = (set: (typeof sets)[number]) => setDraft({ id: set.id, name: set.name, description: set.description ?? "", labels: set.labels.map(label => ({ ...label })), isDefault: Boolean(set.isDefault) });
  const patchLabel = (key: string, patch: Partial<AnnotationLabel>) => setDraft(current => current ? { ...current, labels: current.labels.map(label => label.key === key ? { ...label, ...patch } : label) } : current);
  const save = () => { if (!draft) return; if (!draft.name.trim()) { toast.error("请填写标注集名称"); return; } if (activeLabels.length < 3 || !activeLabels.some(label => label.isNormal)) { toast.error("至少启用三类标签，且需包含一个正常流量标签"); return; } const payload = { name: draft.name.trim(), description: draft.description.trim() || undefined, labels: draft.labels, isDefault: draft.isDefault }; if (draft.id) update.mutate({ id: draft.id, ...payload }); else create.mutate(payload); };
  return <><PageHeader eyebrow="标注配置" title="标注配置" description="配置用于样本标注、模型训练和检测结果展示的类别集合。每个模型和检测任务都会保存当时的标签定义快照。" action={<Button onClick={() => setDraft(freshDraft())} className="bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Plus className="mr-2 h-4 w-4" />新建标注集</Button>} />
    <div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><section className="space-y-3">{sets.map(set => <article key={set.id} className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><p className="text-sm font-semibold text-white">{set.name}</p>{set.isDefault && <Badge className="bg-cyan-300/15 text-cyan-100"><Star className="mr-1 h-3 w-3" />默认</Badge>}{!set.isActive && <Badge variant="outline" className="border-amber-300/20 text-amber-100">已停用</Badge>}</div><p className="mt-1 text-xs text-slate-500">{set.description || "未填写说明"}</p></div><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={() => openEdit(set)}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" disabled={set.isDefault} onClick={() => remove.mutate({ id: set.id! })}><Trash2 className="h-4 w-4 text-rose-200" /></Button></div></div><div className="mt-4 flex flex-wrap gap-2">{set.labels.filter(label => label.enabled).map(label => <Badge key={label.key} variant="outline" className="border-white/10 text-slate-300">{label.name}{label.isNormal ? " · 正常" : ""}</Badge>)}</div><div className="mt-4 flex items-center justify-between border-t border-white/[0.06] pt-3"><div className="flex items-center gap-2"><Switch checked={Boolean(set.isActive)} disabled={set.isDefault} onCheckedChange={checked => update.mutate({ id: set.id!, isActive: checked })} /><span className="text-[11px] text-slate-500">{set.isActive ? "已启用" : "已停用"}{set.isDefault ? " · 默认集不可停用" : ""}</span></div><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={() => setDraft({ name: `${set.name} 副本`, description: set.description ?? "", labels: set.labels.map(label => ({ ...label })), isDefault: false })}><CopyPlus className="mr-1.5 h-3.5 w-3.5" />复制</Button>{!set.isDefault && <Button size="sm" variant="ghost" onClick={() => update.mutate({ id: set.id!, isDefault: true })}>设为默认</Button>}</div></div></article>)}{!sets.length && <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">正在初始化默认标注集。</div>}</section>
      <section className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5">{draft ? <><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-white">{draft.id ? "编辑标注集" : "新建标注集"}</p><p className="mt-1 text-xs text-slate-500">可调整展示名称、启用范围与正常流量基准。</p></div><Badge className="bg-violet-300/10 text-violet-100">{activeLabels.length} 类启用</Badge></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Input value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} placeholder="标注集名称" /><label className="flex items-center gap-3 rounded-lg border border-white/[0.08] px-3 text-sm text-slate-300"><Switch checked={draft.isDefault} onCheckedChange={checked => setDraft({ ...draft, isDefault: checked })} />设为默认集</label></div><Textarea className="mt-3 min-h-20 border-white/10 bg-[#081421] text-slate-200" value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} placeholder="说明该标注集的适用范围" /><div className="mt-5 space-y-2">{draft.labels.map(label => <div key={label.key} className="grid gap-2 rounded-xl border border-white/[0.06] bg-[#081421]/60 p-3 sm:grid-cols-[auto_1fr_auto_auto]"><Switch checked={label.enabled} onCheckedChange={checked => patchLabel(label.key, { enabled: checked })} /><div><p className="text-xs text-slate-500">类别键：{label.key}</p><Input className="mt-1 h-8 border-white/10 bg-white/[0.03] text-sm" value={label.name} onChange={event => patchLabel(label.key, { name: event.target.value })} /></div><label className="flex items-center gap-2 text-xs text-slate-400"><Switch checked={label.isNormal} onCheckedChange={checked => setDraft({ ...draft, labels: draft.labels.map(item => ({ ...item, isNormal: item.key === label.key ? checked : checked ? false : item.isNormal })) })} />正常基准</label><Badge variant="outline" className="h-fit border-white/10 text-slate-500">{label.enabled ? "启用" : "停用"}</Badge></div>)}</div><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setDraft(null)}>取消</Button><Button disabled={create.isPending || update.isPending} onClick={save} className="bg-cyan-300 text-slate-950 hover:bg-cyan-200"><CheckCircle2 className="mr-2 h-4 w-4" />保存标注集</Button></div></> : <div className="grid min-h-96 place-items-center text-center"><div><Pencil className="mx-auto h-8 w-8 text-cyan-200" /><p className="mt-4 text-sm font-medium text-slate-200">选择或新建标注集</p><p className="mt-2 max-w-sm text-xs leading-5 text-slate-500">标注集可配置类别的展示名称、启用状态和正常流量基准；训练和检测将持久化对应快照。</p></div></div>}</section></div></>;
}
