import { PcapDropzone, toBase64 } from "@/components/PcapDropzone";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, FileSearch, ShieldAlert, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type Result = { taskId: number; summary: { packetCount: number; flowCount: number; highRiskFlows: number; averageRisk: number; modelVersion: string; protocolDistribution: Record<string, number> }; topFlows: Array<{ flow: { flowKey: string; sourceIp: string; sourcePort: number; destinationIp: string; destinationPort: number; transportProtocol: string; applicationProtocol: string }; score: number; reasons: string[]; featureValues: Record<string, number> }> };
function riskClass(score: number) { return score >= 0.7 ? "border-rose-400/20 bg-rose-400/10 text-rose-200" : score >= 0.4 ? "border-amber-400/20 bg-amber-400/10 text-amber-200" : "border-emerald-400/20 bg-emerald-400/10 text-emerald-200"; }

export default function Detections() {
  const utils = trpc.useUtils();
  const { data: models = [] } = trpc.models.list.useQuery();
  const [modelId, setModelId] = useState<string>("");
  const [stage, setStage] = useState("等待选择模型和文件");
  const [result, setResult] = useState<Result | null>(null);
  useEffect(() => { const active = models.find(model => model.isActive) ?? models[0]; if (active && !modelId) setModelId(`${active.id}`); }, [models, modelId]);
  const analyze = trpc.detections.analyze.useMutation({ onSuccess: data => { setResult(data); setStage("检测完成，已保存逐流风险评分"); utils.detections.list.invalidate(); utils.dashboard.overview.invalidate(); toast.success("离线检测已完成"); }, onError: error => { setStage("检测失败"); toast.error(error.message); } });
  const handleUpload = async (file: File) => { if (!modelId) { toast.error("请先选择一个模型版本"); return; } setStage("正在读取文件并提取特征"); const fileBase64 = await toBase64(file); setStage("正在运行模型评分并生成可解释原因"); analyze.mutate({ name: file.name, fileBase64, modelId: Number(modelId) }); };
  return <><PageHeader eyebrow="离线研判" title="检测分析" description="选择已保存模型，对待检测 PCAP 提取同构流特征并生成逐流风险评分。高风险流将展示五元组、特征值和评分原因。" />
    <div className="mb-5 rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-white">选择检测模型</p><p className="mt-1 text-xs text-slate-500">模型加载自训练时保存的版本参数</p></div><Select value={modelId} onValueChange={setModelId}><SelectTrigger className="w-full border-white/10 bg-[#081421] text-slate-200 sm:w-80"><SelectValue placeholder="选择模型版本" /></SelectTrigger><SelectContent>{models.map(model => <SelectItem key={model.id} value={`${model.id}`}>{model.versionName}{model.isActive ? " · 当前激活" : ""}</SelectItem>)}</SelectContent></Select></div></div>
    {models.length ? <PcapDropzone onUpload={handleUpload} busy={analyze.isPending} stage={stage} /> : <div className="grid min-h-48 place-items-center rounded-2xl border border-dashed border-white/10 text-center"><div><ShieldAlert className="mx-auto h-8 w-8 text-slate-600" /><p className="mt-3 text-sm text-slate-400">尚无可用模型</p><p className="mt-1 text-xs text-slate-600">请先上传并标注训练数据，然后训练并保存至少一个模型版本。</p></div></div>}
    {result && <section className="mt-6"><div className="grid gap-4 md:grid-cols-4">{[{ label: "检测模型", value: result.summary.modelVersion, icon: ShieldCheck }, { label: "解析流量", value: result.summary.flowCount.toLocaleString(), icon: FileSearch }, { label: "高风险流", value: result.summary.highRiskFlows.toLocaleString(), icon: AlertTriangle }, { label: "平均风险", value: `${(result.summary.averageRisk * 100).toFixed(1)}%`, icon: ShieldAlert }].map(item => <div key={item.label} className="rounded-xl border border-white/[0.08] bg-white/[0.035] p-4"><item.icon className="h-4 w-4 text-cyan-200" /><p className="mt-3 text-[11px] text-slate-500">{item.label}</p><p className="mt-1 truncate text-xl font-semibold text-white">{item.value}</p></div>)}</div><div className="mt-5 overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.035]"><div className="flex items-center justify-between border-b border-white/[0.06] px-5 py-4"><div><p className="text-sm font-semibold text-white">高风险流详情</p><p className="mt-1 text-xs text-slate-500">展示风险评分最高的 10 条流；评分原因来自当前模型的关键偏离特征。</p></div><Badge variant="outline" className="border-white/10 text-slate-400">任务 #{result.taskId}</Badge></div><Table><TableHeader><TableRow className="border-white/[0.06] hover:bg-transparent"><TableHead>五元组</TableHead><TableHead>协议</TableHead><TableHead>评分</TableHead><TableHead>关键特征值</TableHead><TableHead>异常原因</TableHead></TableRow></TableHeader><TableBody>{result.topFlows.map(item => <TableRow key={item.flow.flowKey} className="border-white/[0.06] hover:bg-white/[0.025]"><TableCell className="font-mono text-[10px] leading-5 text-slate-400">{item.flow.sourceIp}:{item.flow.sourcePort}<br />→ {item.flow.destinationIp}:{item.flow.destinationPort}</TableCell><TableCell><Badge variant="outline" className="border-cyan-400/20 text-cyan-200">{item.flow.applicationProtocol}</Badge></TableCell><TableCell><Badge variant="outline" className={riskClass(item.score)}>{(item.score * 100).toFixed(1)}%</Badge></TableCell><TableCell className="max-w-48"><div className="space-y-1 font-mono text-[10px] text-slate-500">{Object.entries(item.featureValues).slice(0, 3).map(([feature, value]) => <p key={feature}>{feature}: {value.toFixed(2)}</p>)}</div></TableCell><TableCell className="max-w-md"><ul className="space-y-1 text-xs leading-5 text-slate-400">{item.reasons.slice(0, 2).map(reason => <li key={reason}>• {reason}</li>)}</ul></TableCell></TableRow>)}</TableBody></Table></div></section>}</>;
}
