import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { trpc } from "@/lib/trpc";
import { trafficClassLabels, trafficClassStyles, type TrafficClass } from "@/lib/trafficClasses";
import { Archive, BrainCircuit, ChevronLeft, ChevronRight, Download, Eye, FileJson, FileSpreadsheet, Radar, ScrollText, Search } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type ExportFormat = "json" | "csv";
type PlainRow = Record<string, unknown>;
const PAGE_SIZE = 10;

function saveFile(name: string, content: string, type: string) { const blob = new Blob([content], { type: `${type};charset=utf-8` }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); }
function stringifyCell(value: unknown) { if (value === null || value === undefined) return ""; if (value instanceof Date) return value.toISOString(); return typeof value === "object" ? JSON.stringify(value) : String(value); }
function toCsv(rows: PlainRow[]) { if (!rows.length) return ""; const columns = Array.from(new Set(rows.flatMap(row => Object.keys(row)))); const quote = (value: unknown) => `"${stringifyCell(value).replace(/"/g, '""')}"`; return `\uFEFF${columns.join(",")}\n${rows.map(row => columns.map(column => quote(row[column])).join(",")).join("\n")}`; }
function formatTime(value: Date | string | null | undefined) { return value ? new Date(value).toLocaleString() : "—"; }
function ExportButton({ onClick, format }: { onClick: () => void; format: ExportFormat }) { return <Button type="button" size="sm" variant="outline" onClick={onClick} className="h-7 border-white/10 bg-white/[0.03] px-2 text-[11px] text-slate-300 hover:bg-white/[0.08]">{format === "json" ? <FileJson className="mr-1 h-3 w-3" /> : <FileSpreadsheet className="mr-1 h-3 w-3" />}{format.toUpperCase()}</Button>; }
function Pager({ page, total, onPage }: { page: number; total: number; onPage: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / PAGE_SIZE)); return <div className="flex items-center justify-between border-t border-white/[0.06] px-4 py-3"><p className="text-xs text-slate-500">共 {total} 条 · 第 {page}/{pages} 页</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page <= 1} onClick={() => onPage(page - 1)} className="border-white/10"><ChevronLeft className="h-3.5 w-3.5" />上一页</Button><Button size="sm" variant="outline" disabled={page >= pages} onClick={() => onPage(page + 1)} className="border-white/10">下一页<ChevronRight className="ml-1 h-3.5 w-3.5" /></Button></div></div>; }
function JsonDetail({ title, data }: { title: string; data: unknown }) { type Nfstream = { source?: string; applicationName?: string | null; application_name?: string | null; bidirectionalPackets?: number | null; bidirectional_packets?: number | null; bidirectionalBytes?: number | null; bidirectional_bytes?: number | null }; const row = data as { id?: number; flowCount?: number; flows?: Array<{ nfstream?: Nfstream | null }>; flowFeatures?: Array<{ nfstream?: Nfstream | null }> } | null; const datasetId = row?.flowCount && row.id ? row.id : 0; const { data: datasetExport } = trpc.history.datasetExport.useQuery({ datasetId }, { enabled: Boolean(datasetId) }); const payload = datasetExport ?? data; const source = payload as { flows?: Array<{ nfstream?: Nfstream | null }>; flowFeatures?: Array<{ nfstream?: Nfstream | null }> } | null; const flows = source?.flows ?? source?.flowFeatures ?? []; const parallel = flows.filter(flow => flow.nfstream?.source === "nfstream"); return <Dialog><DialogTrigger asChild><Button size="sm" variant="ghost" className="h-7 px-2 text-cyan-200 hover:text-cyan-100"><Eye className="mr-1 h-3.5 w-3.5" />详情</Button></DialogTrigger><DialogContent className="max-h-[88vh] max-w-4xl overflow-y-auto border-white/10 bg-[#0b1727] text-slate-100"><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader>{flows.length ? <section className="mt-3 rounded-xl border border-emerald-300/15 bg-emerald-300/[0.035] p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-emerald-100">NFStream 历史持久化</p><Badge variant="outline" className="border-emerald-400/25 text-emerald-200">{parallel.length} / {flows.length} 已关联</Badge></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{parallel.slice(0, 6).map((flow, index) => <div key={index} className="rounded-lg bg-black/15 p-2 text-[11px]"><p className="text-slate-300">{flow.nfstream?.applicationName ?? flow.nfstream?.application_name ?? "未识别应用"}</p><p className="mt-1 text-slate-500">{flow.nfstream?.source} · 双向 {flow.nfstream?.bidirectionalPackets ?? flow.nfstream?.bidirectional_packets ?? "—"} 包 / {flow.nfstream?.bidirectionalBytes ?? flow.nfstream?.bidirectional_bytes ?? "—"} B</p></div>)}</div>{!parallel.length ? <p className="mt-3 text-xs text-amber-100">该历史记录未关联 NFStream 流，已保留原生解析回退结果。</p> : null}</section> : null}<pre className="mt-3 overflow-x-auto rounded-xl border border-white/[0.08] bg-black/20 p-4 text-xs leading-6 text-slate-300">{JSON.stringify(payload, null, 2)}</pre></DialogContent></Dialog>; }

export default function History() {
  const [keyword, setKeyword] = useState(""); const [tab, setTab] = useState("datasets"); const [page, setPage] = useState(1); const query = { page, pageSize: PAGE_SIZE, keyword: keyword || undefined };
  const { data: datasetPage } = trpc.history.datasets.useQuery(query); const { data: modelPage } = trpc.history.models.useQuery(query); const { data: detectionPage } = trpc.history.detections.useQuery(query); const { data: logPage } = trpc.history.operationLogs.useQuery(query); const { data: allLogs = [] } = trpc.history.logs.useQuery({ limit: 500 }); const utils = trpc.useUtils();
  const datasets = datasetPage?.items ?? []; const models = modelPage?.items ?? []; const detections = detectionPage?.items ?? []; const logs = logPage?.items ?? [];
  const setHistoryTab = (next: string) => { setTab(next); setPage(1); };
  const updateKeyword = (value: string) => { setKeyword(value); setPage(1); };
  const downloadDataset = async (id: number, name: string, format: ExportFormat) => { try { const data = await utils.history.datasetExport.fetch({ datasetId: id }); const safe = name.replace(/[^a-zA-Z0-9._-]/g, "_"); format === "json" ? saveFile(`${safe}_dataset.json`, JSON.stringify(data, null, 2), "application/json") : saveFile(`${safe}_flows.csv`, toCsv(data.flowFeatures as unknown as PlainRow[]), "text/csv"); toast.success(`已下载 ${format.toUpperCase()} 训练数据`); } catch (error) { toast.error(error instanceof Error ? error.message : "数据集导出失败"); } };
  const downloadModel = async (id: number, name: string, format: ExportFormat) => { try { const data = await utils.history.modelExport.fetch({ modelId: id }); const safe = name.replace(/[^a-zA-Z0-9._-]/g, "_"); format === "json" ? saveFile(`${safe}_model.json`, JSON.stringify(data, null, 2), "application/json") : saveFile(`${safe}_model.csv`, toCsv([data as unknown as PlainRow]), "text/csv"); toast.success(`已下载 ${format.toUpperCase()} 模型信息`); } catch (error) { toast.error(error instanceof Error ? error.message : "模型导出失败"); } };
  const downloadDetection = async (id: number, name: string, format: ExportFormat) => { try { const data = await utils.history.detectionExport.fetch({ taskId: id }); if (!data) throw new Error("检测任务不存在"); const safe = name.replace(/[^a-zA-Z0-9._-]/g, "_"); format === "json" ? saveFile(`${safe}_detection.json`, JSON.stringify(data, null, 2), "application/json") : saveFile(`${safe}_flows.csv`, toCsv(data.flows as unknown as PlainRow[]), "text/csv"); toast.success(`已下载 ${format.toUpperCase()} 检测结果`); } catch (error) { toast.error(error instanceof Error ? error.message : "检测结果导出失败"); } };
  const downloadLogs = (format: ExportFormat) => { format === "json" ? saveFile("trafficguard_operation_logs.json", JSON.stringify(allLogs, null, 2), "application/json") : saveFile("trafficguard_operation_logs.csv", toCsv(allLogs as unknown as PlainRow[]), "text/csv"); toast.success(`已下载 ${format.toUpperCase()} 操作日志`); };
  return <><PageHeader eyebrow="历史归档" title="历史归档" description="集中查看、检索和下载已持久化的训练数据、模型版本、检测结果及操作审计日志。" /><div className="mb-5 grid gap-3 sm:grid-cols-4">{[{ label: "训练数据", value: datasetPage?.total ?? 0, icon: Archive }, { label: "模型版本", value: modelPage?.total ?? 0, icon: BrainCircuit }, { label: "检测任务", value: detectionPage?.total ?? 0, icon: Radar }, { label: "审计日志", value: logPage?.total ?? 0, icon: ScrollText }].map(item => <div key={item.label} className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-4"><item.icon className="h-4 w-4 text-cyan-200" /><p className="mt-3 text-[11px] text-slate-500">{item.label}</p><p className="mt-1 text-xl font-semibold text-white">{item.value}</p></div>)}</div><div className="mb-5 flex items-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.035] px-3"><Search className="h-4 w-4 text-slate-500" /><Input value={keyword} onChange={event => updateKeyword(event.target.value)} placeholder="检索文件名、模型版本、类别、任务或操作…" className="border-0 bg-transparent px-0 text-sm text-slate-200 placeholder:text-slate-600 focus-visible:ring-0" /></div>
    <Tabs value={tab} onValueChange={setHistoryTab} className="space-y-4"><TabsList className="h-auto flex-wrap justify-start gap-1 bg-transparent p-0"><TabsTrigger value="datasets" className="data-[state=active]:bg-cyan-300 data-[state=active]:text-slate-950">训练数据</TabsTrigger><TabsTrigger value="models" className="data-[state=active]:bg-cyan-300 data-[state=active]:text-slate-950">模型版本</TabsTrigger><TabsTrigger value="detections" className="data-[state=active]:bg-cyan-300 data-[state=active]:text-slate-950">检测结果</TabsTrigger><TabsTrigger value="logs" className="data-[state=active]:bg-cyan-300 data-[state=active]:text-slate-950">操作日志</TabsTrigger></TabsList>
      <TabsContent value="datasets" className="m-0"><div className="overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.035]"><Table><TableHeader><TableRow className="border-white/[0.06] hover:bg-transparent"><TableHead>训练数据</TableHead><TableHead>类别</TableHead><TableHead>包 / 流</TableHead><TableHead>创建时间</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{datasets.map(item => <TableRow key={item.id} className="border-white/[0.06]"><TableCell><p className="font-medium text-slate-200">{item.name}</p><p className="mt-1 text-[11px] text-slate-500">#{item.id} · {(item.fileSize / 1024).toFixed(1)} KB</p></TableCell><TableCell><Badge variant="outline" className={trafficClassStyles[item.trafficClass as TrafficClass]}>{trafficClassLabels[item.trafficClass as TrafficClass] ?? item.trafficClass}</Badge></TableCell><TableCell className="text-xs text-slate-400">{item.packetCount} / {item.flowCount}</TableCell><TableCell className="text-xs text-slate-500">{formatTime(item.createdAt)}</TableCell><TableCell><div className="flex justify-end gap-1"><JsonDetail title={`训练数据详情 · ${item.name}`} data={item} /><ExportButton format="json" onClick={() => downloadDataset(item.id, item.name, "json")} /><ExportButton format="csv" onClick={() => downloadDataset(item.id, item.name, "csv")} /></div></TableCell></TableRow>)}{!datasets.length && <TableRow><TableCell colSpan={5} className="h-24 text-center text-sm text-slate-500">暂无匹配的训练数据</TableCell></TableRow>}</TableBody></Table><Pager page={page} total={datasetPage?.total ?? 0} onPage={setPage} /></div></TabsContent>
      <TabsContent value="models" className="m-0"><div className="overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.035]"><Table><TableHeader><TableRow className="border-white/[0.06] hover:bg-transparent"><TableHead>模型版本</TableHead><TableHead>算法 / 类别</TableHead><TableHead>状态</TableHead><TableHead>创建时间</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{models.map(item => <TableRow key={item.id} className="border-white/[0.06]"><TableCell><p className="font-medium text-slate-200">{item.versionName}</p><p className="mt-1 text-[11px] text-slate-500">#{item.id}</p></TableCell><TableCell className="text-xs text-slate-400">{item.algorithm} · {(JSON.parse(item.classSetJson) as string[]).length} 类</TableCell><TableCell>{item.isActive ? <Badge className="bg-cyan-300 text-slate-950">当前激活</Badge> : <Badge variant="outline" className="border-white/10 text-slate-500">历史版本</Badge>}</TableCell><TableCell className="text-xs text-slate-500">{formatTime(item.createdAt)}</TableCell><TableCell><div className="flex justify-end gap-1"><JsonDetail title={`模型版本详情 · ${item.versionName}`} data={item} /><ExportButton format="json" onClick={() => downloadModel(item.id, item.versionName, "json")} /><ExportButton format="csv" onClick={() => downloadModel(item.id, item.versionName, "csv")} /></div></TableCell></TableRow>)}{!models.length && <TableRow><TableCell colSpan={5} className="h-24 text-center text-sm text-slate-500">暂无匹配的模型版本</TableCell></TableRow>}</TableBody></Table><Pager page={page} total={modelPage?.total ?? 0} onPage={setPage} /></div></TabsContent>
      <TabsContent value="detections" className="m-0"><div className="overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.035]"><Table><TableHeader><TableRow className="border-white/[0.06] hover:bg-transparent"><TableHead>检测任务</TableHead><TableHead>模型</TableHead><TableHead>流量 / 高风险</TableHead><TableHead>平均风险</TableHead><TableHead>创建时间</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{detections.map(item => <TableRow key={item.id} className="border-white/[0.06]"><TableCell><p className="font-medium text-slate-200">{item.fileName}</p><p className="mt-1 text-[11px] text-slate-500">任务 #{item.id} · {item.status}</p></TableCell><TableCell className="text-xs text-slate-400">#{item.modelVersionId}</TableCell><TableCell className="text-xs text-slate-400">{item.totalFlows} / <span className="text-rose-200">{item.highRiskFlows}</span></TableCell><TableCell className="text-xs text-slate-300">{(item.averageRisk * 100).toFixed(1)}%</TableCell><TableCell className="text-xs text-slate-500">{formatTime(item.createdAt)}</TableCell><TableCell><div className="flex justify-end gap-1"><DetectionDetail taskId={item.id} fileName={item.fileName} /><ExportButton format="json" onClick={() => downloadDetection(item.id, item.fileName, "json")} /><ExportButton format="csv" onClick={() => downloadDetection(item.id, item.fileName, "csv")} /></div></TableCell></TableRow>)}{!detections.length && <TableRow><TableCell colSpan={6} className="h-24 text-center text-sm text-slate-500">暂无匹配的检测任务</TableCell></TableRow>}</TableBody></Table><Pager page={page} total={detectionPage?.total ?? 0} onPage={setPage} /></div></TabsContent>
      <TabsContent value="logs" className="m-0"><div className="rounded-2xl border border-white/[0.08] bg-white/[0.035]"><div className="flex items-center justify-between border-b border-white/[0.06] p-4"><div><p className="text-sm font-semibold text-white">操作审计日志</p><p className="mt-1 text-xs text-slate-500">持续记录上传、标注、训练、模型、检测和接口密钥操作。</p></div><div className="flex gap-1"><ExportButton format="json" onClick={() => downloadLogs("json")} /><ExportButton format="csv" onClick={() => downloadLogs("csv")} /></div></div><div className="divide-y divide-white/[0.06]">{logs.map(log => <div key={log.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Badge variant="outline" className="border-cyan-300/20 text-cyan-100">{log.action}</Badge><p className="text-sm text-slate-200">{log.summary}</p></div><p className="mt-1 font-mono text-[11px] text-slate-600">{log.entityType} #{log.entityId ?? "—"} · {JSON.stringify(log.metadata)}</p></div><p className="shrink-0 text-xs text-slate-500">{formatTime(log.createdAt)}</p></div>)}{!logs.length && <div className="p-10 text-center text-sm text-slate-500">暂无匹配的操作日志。</div>}</div><Pager page={page} total={logPage?.total ?? 0} onPage={setPage} /></div></TabsContent>
    </Tabs></>;
}

function DetectionDetail({ taskId, fileName }: { taskId: number; fileName: string }) { const { data } = trpc.history.detectionExport.useQuery({ taskId }); return <JsonDetail title={`检测任务详情 · ${fileName}`} data={data ?? { loading: true }} />; }
