import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, CircleDashed, Gauge, Layers3 } from "lucide-react";
import { toast } from "sonner";

export default function Models() {
  const utils = trpc.useUtils();
  const { data: models = [], isLoading } = trpc.models.list.useQuery();
  const activate = trpc.models.activate.useMutation({ onSuccess: () => { utils.models.list.invalidate(); utils.dashboard.overview.invalidate(); toast.success("当前检测模型已切换"); }, onError: error => toast.error(error.message) });
  return <><PageHeader eyebrow="模型仓库" title="模型版本管理" description="每次训练自动保存参数、特征集、训练数据引用和评估指标。可随时激活指定版本供检测任务使用。" />
    <div className="grid gap-4 lg:grid-cols-2">{isLoading ? <p className="text-sm text-slate-500">正在加载模型版本…</p> : models.length ? models.map(model => { const metrics = JSON.parse(model.metricsJson) as Record<string, number>; const features = JSON.parse(model.featureSetJson) as string[]; return <Card key={model.id} className={`border p-5 ${model.isActive ? "border-cyan-300/35 bg-cyan-300/[0.06]" : "border-white/[0.08] bg-white/[0.035]"}`}><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><p className="text-lg font-semibold text-white">{model.versionName}</p>{model.isActive && <Badge className="bg-cyan-300 text-slate-950 hover:bg-cyan-300">当前激活</Badge>}</div><p className="mt-1 text-xs text-slate-500">{model.algorithm === "logistic_regression" ? "逻辑回归" : "高斯朴素贝叶斯"} · {new Date(model.createdAt).toLocaleString()}</p></div><div className="grid h-9 w-9 place-items-center rounded-xl bg-white/[0.06] text-cyan-200"><Gauge className="h-4 w-4" /></div></div><div className="mt-5 grid grid-cols-4 gap-2">{["accuracy", "precision", "recall", "f1"].map(metric => <div key={metric} className="rounded-lg bg-[#081421]/60 p-2 text-center"><p className="text-[9px] uppercase tracking-wide text-slate-500">{metric}</p><p className="mt-1 text-sm font-semibold text-slate-200">{((metrics[metric] ?? 0) * 100).toFixed(1)}%</p></div>)}</div><div className="mt-4 flex flex-wrap gap-1.5">{features.map(feature => <Badge key={feature} variant="outline" className="border-white/10 bg-white/[0.025] text-[10px] text-slate-400">{feature}</Badge>)}</div><div className="mt-5 flex justify-between border-t border-white/[0.07] pt-4"><span className="inline-flex items-center gap-1.5 text-xs text-slate-500"><Layers3 className="h-3.5 w-3.5" />模型参数已持久化</span>{model.isActive ? <span className="inline-flex items-center gap-1 text-xs text-cyan-200"><CheckCircle2 className="h-3.5 w-3.5" />可直接检测</span> : <Button size="sm" variant="outline" onClick={() => activate.mutate({ modelId: model.id })} className="h-8 border-white/10 bg-white/[0.03] text-xs text-slate-200 hover:bg-white/[0.08]">加载为当前模型</Button>}</div></Card>; }) : <div className="col-span-full grid min-h-64 place-items-center rounded-2xl border border-dashed border-white/10"><div className="text-center"><CircleDashed className="mx-auto h-9 w-9 text-slate-600" /><p className="mt-3 text-sm text-slate-400">暂无可用模型版本</p><p className="mt-1 text-xs text-slate-600">完成一次包含良性和恶意样本的训练后，模型将显示在此处。</p></div></div>}</div></>;
}
