import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { BrainCircuit, CheckCircle2, Loader2, SlidersHorizontal } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const featureOptions = ["packetCount", "byteCount", "durationMs", "avgPacketLength", "stdPacketLength", "avgIatMs", "stdIatMs", "uplinkRatio", "upPackets", "downPackets"] as const;
const featureLabels: Record<(typeof featureOptions)[number], string> = { packetCount: "包数量", byteCount: "总字节数", durationMs: "持续时间", avgPacketLength: "平均包长", stdPacketLength: "包长波动", avgIatMs: "平均 IAT", stdIatMs: "IAT 波动", uplinkRatio: "上行占比", upPackets: "上行包数", downPackets: "下行包数" };

export default function Training() {
  const utils = trpc.useUtils();
  const { data: datasets = [] } = trpc.datasets.list.useQuery();
  const eligible = datasets.filter(dataset => dataset.label !== "unlabeled");
  const [selected, setSelected] = useState<number[]>([]);
  const [features, setFeatures] = useState<(typeof featureOptions)[number][]>(["packetCount", "byteCount", "durationMs", "avgPacketLength", "avgIatMs", "uplinkRatio"]);
  const [algorithm, setAlgorithm] = useState<"logistic_regression" | "gaussian_nb">("logistic_regression");
  const [jobId, setJobId] = useState<number | null>(null);
  const [result, setResult] = useState<{ versionName: string; metrics: { accuracy: number; precision: number; recall: number; f1: number }; trainingCount: number; validationCount: number } | null>(null);
  const train = trpc.models.train.useMutation({ onSuccess: data => { setResult(data); utils.models.list.invalidate(); utils.dashboard.overview.invalidate(); toast.success(`训练完成，已保存 ${data.versionName}`); }, onError: error => toast.error(error.message) });
  const createJob = trpc.models.createTrainingJob.useMutation({ onSuccess: (nextJobId, variables) => { setJobId(nextJobId); train.mutate({ ...variables, jobId: nextJobId }); }, onError: error => toast.error(error.message) });
  const { data: job } = trpc.models.trainingJob.useQuery({ jobId: jobId ?? 0 }, { enabled: Boolean(jobId), refetchInterval: 500 });
  const selectionCounts = useMemo(() => ({ benign: selected.filter(id => datasets.find(dataset => dataset.id === id)?.label === "benign").length, malicious: selected.filter(id => datasets.find(dataset => dataset.id === id)?.label === "malicious").length }), [datasets, selected]);
  const toggleDataset = (id: number) => setSelected(previous => previous.includes(id) ? previous.filter(value => value !== id) : [...previous, id]);
  const toggleFeature = (feature: (typeof featureOptions)[number]) => setFeatures(previous => previous.includes(feature) ? previous.filter(value => value !== feature) : [...previous, feature]);
  const start = () => { if (selectionCounts.benign < 1 || selectionCounts.malicious < 1) { toast.error("至少选择一个良性数据集和一个恶意数据集"); return; } if (features.length < 3) { toast.error("至少选择三个特征"); return; } setResult(null); setJobId(null); createJob.mutate({ datasetIds: selected, features, algorithm }); };
  return <><PageHeader eyebrow="训练实验" title="模型训练" description="从已标注 PCAP 的流特征中训练轻量机器学习模型。训练完成后，模型参数和指标会自动保存为新的版本。" />
    <div className="grid gap-5 xl:grid-cols-[1fr_.9fr]"><div className="space-y-5"><section className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-white">1. 选择训练数据集</p><p className="mt-1 text-xs text-slate-500">必须同时选择良性和恶意数据集</p></div><p className="text-xs text-slate-500">良性 {selectionCounts.benign} · 恶意 {selectionCounts.malicious}</p></div><div className="mt-4 space-y-2">{eligible.length ? eligible.map(dataset => <label key={dataset.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/[0.06] bg-[#081421]/50 p-3 hover:border-cyan-300/20"><Checkbox checked={selected.includes(dataset.id)} onCheckedChange={() => toggleDataset(dataset.id)} /><span className="flex-1"><span className="block text-sm text-slate-200">{dataset.name}</span><span className="mt-1 block text-[11px] text-slate-500">{dataset.flowCount} 条流 · {dataset.label === "benign" ? "良性" : "恶意"}</span></span><span className={`rounded-full px-2 py-1 text-[10px] ${dataset.label === "benign" ? "bg-emerald-400/10 text-emerald-200" : "bg-rose-400/10 text-rose-200"}`}>{dataset.label}</span></label>) : <p className="rounded-xl border border-dashed border-white/10 p-5 text-center text-sm text-slate-500">请先上传并标注至少一个良性和一个恶意 PCAP 数据集。</p>}</div></section>
      <section className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><p className="text-sm font-semibold text-white">2. 配置训练参数</p><div className="mt-4"><p className="mb-2 text-xs text-slate-500">算法</p><Select value={algorithm} onValueChange={value => setAlgorithm(value as typeof algorithm)}><SelectTrigger className="border-white/10 bg-[#081421] text-slate-200"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="logistic_regression">逻辑回归 · 可解释风险概率</SelectItem><SelectItem value="gaussian_nb">高斯朴素贝叶斯 · 快速基线</SelectItem></SelectContent></Select></div><div className="mt-5"><p className="mb-2 text-xs text-slate-500">流量特征集（至少 3 项）</p><div className="grid gap-2 sm:grid-cols-2">{featureOptions.map(feature => <label key={feature} className="flex cursor-pointer items-center gap-2 rounded-lg border border-white/[0.06] bg-[#081421]/50 px-3 py-2.5 text-xs text-slate-300"><Checkbox checked={features.includes(feature)} onCheckedChange={() => toggleFeature(feature)} />{featureLabels[feature]}</label>)}</div></div></section></div>
      <aside className="rounded-2xl border border-cyan-300/15 bg-gradient-to-b from-cyan-300/[0.08] to-white/[0.025] p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300 text-slate-950"><BrainCircuit className="h-5 w-5" /></div><div><p className="text-sm font-semibold text-white">训练执行</p><p className="text-xs text-slate-500">带有 80/20 固定验证划分</p></div></div><Button disabled={train.isPending || createJob.isPending || !eligible.length} onClick={start} className="mt-6 w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{train.isPending || createJob.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />正在训练</> : <><SlidersHorizontal className="mr-2 h-4 w-4" />开始训练并保存版本</>}</Button>{(train.isPending || createJob.isPending) && <div className="mt-5"><div className="mb-2 flex justify-between text-xs text-slate-400"><span>{job?.progress && job.progress >= 60 ? "模型拟合与验证评估" : job?.progress && job.progress >= 30 ? "已加载标注流，正在准备特征" : "正在创建训练任务"}</span><span>{job?.progress ?? 10}%</span></div><Progress value={job?.progress ?? 10} className="h-1.5 bg-white/10" /></div>}{result ? <div className="mt-6 rounded-xl border border-emerald-400/15 bg-emerald-400/[0.07] p-4"><div className="flex items-center gap-2 text-emerald-200"><CheckCircle2 className="h-4 w-4" /><span className="text-sm font-medium">已保存 {result.versionName}</span></div><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(result.metrics).filter(([key]) => ["accuracy", "precision", "recall", "f1"].includes(key)).map(([key, value]) => <div key={key} className="rounded-lg bg-black/15 p-2.5"><p className="text-[10px] uppercase text-emerald-100/60">{key}</p><p className="mt-1 text-lg font-semibold text-emerald-100">{(Number(value) * 100).toFixed(1)}%</p></div>)}</div><p className="mt-3 text-[11px] text-emerald-100/60">训练 {result.trainingCount} 条流 · 验证 {result.validationCount} 条流</p></div> : <p className="mt-6 text-xs leading-5 text-slate-500">模型会保存特征集、算法、训练数据引用、权重和评估指标。首个模型自动设置为当前检测模型。</p>}</aside></div></>;
}
