import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { BrainCircuit, CheckCircle2, Loader2, SlidersHorizontal } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const featureOptions = ["packetCount", "byteCount", "durationMs", "avgPacketLength", "stdPacketLength", "avgIatMs", "stdIatMs", "uplinkRatio", "upPackets", "downPackets"] as const;
const featureLabels: Record<(typeof featureOptions)[number], string> = { packetCount: "包数量", byteCount: "总字节数", durationMs: "持续时间", avgPacketLength: "平均包长", stdPacketLength: "包长波动", avgIatMs: "平均 IAT", stdIatMs: "IAT 波动", uplinkRatio: "上行占比", upPackets: "上行包数", downPackets: "下行包数" };

export default function Training() {
  const utils = trpc.useUtils(); const { data: datasets = [] } = trpc.datasets.list.useQuery(); const { data: annotationSetResults = [] } = trpc.annotationSets.list.useQuery(); const annotationSets = annotationSetResults.filter(set => set.isActive);
  const [annotationSetId, setAnnotationSetId] = useState<number | undefined>(); const annotationSet = annotationSets.find(set => set.id === annotationSetId) ?? annotationSets.find(set => set.id && set.name) ?? null;
  useEffect(() => { if (!annotationSetId && annotationSets[0]?.id) setAnnotationSetId(annotationSets.find(set => set.id && set.name)?.id); }, [annotationSetId, annotationSets]);
  const labels = annotationSet?.labels.filter(label => label.enabled) ?? []; const labelNames = Object.fromEntries(labels.map(label => [label.key, label.name]));
  const eligible = datasets.filter(dataset => dataset.trafficClass !== "unlabeled" && (!annotationSet?.id || dataset.annotationSetId === annotationSet.id));
  const [selected, setSelected] = useState<number[]>([]); const [features, setFeatures] = useState<(typeof featureOptions)[number][]>(["packetCount", "byteCount", "durationMs", "avgPacketLength", "avgIatMs", "uplinkRatio"]); const [algorithm, setAlgorithm] = useState<"lightgbm_kitnet">("lightgbm_kitnet"); const [jobId, setJobId] = useState<number | null>(null);
  const [result, setResult] = useState<{ versionName: string; classes: string[]; metrics: { accuracy: number; precision: number; recall: number; f1: number }; trainingCount: number; validationCount: number } | null>(null);
  const train = trpc.models.train.useMutation({ onSuccess: data => { setResult(data); utils.models.list.invalidate(); utils.dashboard.overview.invalidate(); toast.success(`训练完成，已保存 ${data.versionName}`); }, onError: error => toast.error(error.message) });
  const createJob = trpc.models.createTrainingJob.useMutation({ onSuccess: (nextJobId, variables) => { setJobId(nextJobId); train.mutate({ ...variables, jobId: nextJobId }); }, onError: error => toast.error(error.message) });
  const { data: job } = trpc.models.trainingJob.useQuery({ jobId: jobId ?? 0 }, { enabled: Boolean(jobId), refetchInterval: 500 });
  const selectedClasses = useMemo(() => Array.from(new Set(selected.map(id => datasets.find(dataset => dataset.id === id)?.trafficClass).filter((value): value is string => Boolean(value && value !== "unlabeled")))), [datasets, selected]);
  const toggleDataset = (id: number) => setSelected(previous => previous.includes(id) ? previous.filter(value => value !== id) : [...previous, id]); const toggleFeature = (feature: (typeof featureOptions)[number]) => setFeatures(previous => previous.includes(feature) ? previous.filter(value => value !== feature) : [...previous, feature]);
  const start = () => { if (!annotationSet?.id) { toast.error("请先选择标注集"); return; } const normalKey = labels.find(label => label.isNormal)?.key; if (!normalKey || !selectedClasses.includes(normalKey) || selectedClasses.length < 3) { toast.error("所选数据需包含标注集中的正常类别和至少两种其他类别"); return; } if (features.length < 3) { toast.error("至少选择三个特征"); return; } setResult(null); setJobId(null); createJob.mutate({ datasetIds: selected, annotationSetId: annotationSet.id, features, algorithm }); };
  return <><PageHeader eyebrow="模型训练" title="模型训练" description="选择标注集后，从已标注 PCAP 的流特征中训练多分类模型；标签定义快照将随模型版本持久化保存。" />
    <div className="grid gap-5 xl:grid-cols-[1fr_.9fr]"><div className="space-y-5"><section className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-white">1. 选择标注集与训练数据</p><p className="mt-1 text-xs text-slate-500">仅显示与所选标注集关联的已标注数据集。</p></div><Select value={annotationSet?.id?.toString()} onValueChange={value => { setAnnotationSetId(Number(value)); setSelected([]); }}><SelectTrigger className="w-52 border-white/10 bg-[#081421] text-slate-200"><SelectValue placeholder="选择标注集" /></SelectTrigger><SelectContent>{annotationSets.filter(set => set.labels.some(label => label.enabled)).map(set => <SelectItem key={set.id} value={String(set.id)}>{set.name}</SelectItem>)}</SelectContent></Select></div><p className="mt-3 text-xs text-cyan-200">{selectedClasses.length ? selectedClasses.map(value => labelNames[value] ?? value).join(" · ") : "尚未选择类别"}</p><div className="mt-4 space-y-2">{eligible.length ? eligible.map(dataset => { const itemClass = dataset.trafficClass; return <label key={dataset.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/[0.06] bg-[#081421]/50 p-3 hover:border-cyan-300/20"><Checkbox checked={selected.includes(dataset.id)} onCheckedChange={() => toggleDataset(dataset.id)} /><span className="flex-1"><span className="block text-sm text-slate-200">{dataset.name}</span><span className="mt-1 block text-[11px] text-slate-500">{dataset.flowCount} 条流 · {labelNames[itemClass] ?? itemClass}</span></span><span className="rounded-full bg-cyan-300/10 px-2 py-1 text-[10px] text-cyan-100">{labelNames[itemClass] ?? itemClass}</span></label>; }) : <p className="rounded-xl border border-dashed border-white/10 p-5 text-center text-sm text-slate-500">当前标注集没有可训练数据。请在样本上传或数据管理中使用该标注集完成至少三类标注。</p>}</div></section>
      <section className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><p className="text-sm font-semibold text-white">2. 配置训练参数</p><div className="mt-4 rounded-xl border border-cyan-300/15 bg-cyan-300/[0.06] p-3"><p className="text-sm font-medium text-cyan-100">LightGBM + Kitsune KitNET</p><p className="mt-1 text-xs leading-5 text-slate-400">采用方案指定的开源监督多分类与无监督异常检测融合模型；模型工件和标注集快照将随版本持久化。</p></div><div className="mt-5"><p className="mb-2 text-xs text-slate-500">流量特征集（至少 3 项）</p><div className="grid gap-2 sm:grid-cols-2">{featureOptions.map(feature => <label key={feature} className="flex cursor-pointer items-center gap-2 rounded-lg border border-white/[0.06] bg-[#081421]/50 px-3 py-2.5 text-xs text-slate-300"><Checkbox checked={features.includes(feature)} onCheckedChange={() => toggleFeature(feature)} />{featureLabels[feature]}</label>)}</div></div></section></div>
      <aside className="rounded-2xl border border-cyan-300/15 bg-gradient-to-b from-cyan-300/[0.08] to-white/[0.025] p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300 text-slate-950"><BrainCircuit className="h-5 w-5" /></div><div><p className="text-sm font-semibold text-white">训练执行</p><p className="text-xs text-slate-500">标注集快照将写入模型版本</p></div></div><Button disabled={train.isPending || createJob.isPending || !eligible.length} onClick={start} className="mt-6 w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{train.isPending || createJob.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />正在训练</> : <><SlidersHorizontal className="mr-2 h-4 w-4" />开始训练并保存版本</>}</Button>{(train.isPending || createJob.isPending) && <div className="mt-5"><div className="mb-2 flex justify-between text-xs text-slate-400"><span>{job?.progress && job.progress >= 60 ? "模型拟合与验证评估" : job?.progress && job.progress >= 30 ? "已加载标注流，正在准备特征" : "正在创建训练任务"}</span><span>{job?.progress ?? 10}%</span></div><Progress value={job?.progress ?? 10} className="h-1.5 bg-white/10" /></div>}{result ? <div className="mt-6 rounded-xl border border-emerald-400/15 bg-emerald-400/[0.07] p-4"><div className="flex items-center gap-2 text-emerald-200"><CheckCircle2 className="h-4 w-4" /><span className="text-sm font-medium">已保存 {result.versionName}</span></div><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(result.metrics).map(([key, value]) => <div key={key} className="rounded-lg bg-black/15 p-2.5"><p className="text-[10px] uppercase text-emerald-100/60">{key}</p><p className="mt-1 text-lg font-semibold text-emerald-100">{(Number(value) * 100).toFixed(1)}%</p></div>)}</div><p className="mt-3 text-[11px] text-emerald-100/60">训练 {result.trainingCount} 条流 · 验证 {result.validationCount} 条流</p></div> : <p className="mt-6 text-xs leading-5 text-slate-500">模型会保存标注集快照、特征集、算法、训练数据引用、权重和评估指标。</p>}</aside></div></>;
}
