import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { AVAILABLE_ANNOTATION_KEYS, type AnnotationLabel, type AnnotationSetSnapshot } from "@shared/annotationSets";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, router } from "./_core/trpc";
import { activateModel, createAnnotationSet, createApiKey, createDataset, createUploadTask, createDetectionTask, createModel, createTrainingJob, dashboard, deleteAnnotationSet, deleteDataset, exportDataset, exportModel, getAnnotationSet, getDataset, getDetectionTask, getModel, getPublicWorkspaceUser, getTrainingJob, getUploadTask, getTrainingSamples, insertDetectionFlows, insertFlowFeatures, listAnnotationSets, listDatasetFeatures, listDatasetHistory, listDatasets, listDetectionHistory, listDetectionTasks, listApiKeys, listModelHistory, listModels, listOperationLogHistory, listOperationLogs, updateAnnotationSet, updateDatasetLabel, updateTrainingJob, updateUploadTask, revokeApiKey } from "./db";
import { FEATURE_OPTIONS, TRAFFIC_CLASSES, trainModel, type FeatureName, type ModelAlgorithm, type TrafficClass } from "./modelEngine";
import { storageGetSignedUrl, storagePut } from "./storage";
import { analyzePcapWithNfstream } from "./nfstream";
import { inspectPcap } from "./detectionService";

const MAX_UPLOAD_BYTES = 20 * 1024 * 1024;
const trafficClasses = z.enum(TRAFFIC_CLASSES); const datasetClasses = z.union([trafficClasses, z.literal("unlabeled")]); const algorithms = z.literal("lightgbm_kitnet"); const featureNames = z.enum(FEATURE_OPTIONS);
const annotationLabelSchema = z.object({ key: z.enum(AVAILABLE_ANNOTATION_KEYS), name: z.string().min(1).max(40), description: z.string().max(120).optional(), enabled: z.boolean(), isNormal: z.boolean() });
const annotationSetSchema = z.object({ name: z.string().min(2).max(96), description: z.string().max(255).optional(), labels: z.array(annotationLabelSchema).min(3).max(AVAILABLE_ANNOTATION_KEYS.length), isDefault: z.boolean().optional() }).superRefine((value, ctx) => { const keys = value.labels.map(label => label.key); if (new Set(keys).size !== keys.length) ctx.addIssue({ code: "custom", message: "标签键不能重复" }); if (!value.labels.some(label => label.enabled && label.isNormal)) ctx.addIssue({ code: "custom", message: "标注集至少需要一个启用的正常流量标签" }); if (value.labels.filter(label => label.enabled).length < 3) ctx.addIssue({ code: "custom", message: "标注集至少需要三个启用类别" }); });
const historyPageInput = z.object({ page: z.number().int().positive().default(1), pageSize: z.number().int().min(5).max(100).default(10), keyword: z.string().max(120).optional() });
function decodePcap(base64: string) { const encoded = base64.includes(",") ? base64.split(",").at(-1)! : base64; const buffer = Buffer.from(encoded, "base64"); if (!buffer.length) throw new Error("上传内容为空"); if (buffer.length > MAX_UPLOAD_BYTES) throw new Error("单个 PCAP 文件不能超过 20 MB"); return buffer; }
function safeName(name: string) { return name.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 160) || "capture.pcap"; }
function snapshotFromJob(job: { annotationSnapshotJson: string | null }) { if (!job.annotationSnapshotJson) throw new Error("训练任务缺少标注集快照"); return JSON.parse(job.annotationSnapshotJson) as AnnotationSetSnapshot; }
function assertLabelInSet(annotationSet: AnnotationSetSnapshot, trafficClass: TrafficClass | "unlabeled") { if (trafficClass === "unlabeled") return; if (!annotationSet.labels.some(label => label.key === trafficClass && label.enabled)) throw new Error("所选类别不属于当前启用的标注集"); }
const workspaceProcedure = publicProcedure.use(async ({ ctx, next }) => next({ ctx: { ...ctx, workspaceUser: await getPublicWorkspaceUser() } }));

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(() => getPublicWorkspaceUser()), logout: publicProcedure.mutation(({ ctx }) => { ctx.res.clearCookie(COOKIE_NAME, { ...getSessionCookieOptions(ctx.req), maxAge: -1 }); return { success: true } as const; }) }),
  dashboard: router({ overview: workspaceProcedure.query(({ ctx }) => dashboard(ctx.workspaceUser.id)) }),
  annotationSets: router({
    list: workspaceProcedure.query(({ ctx }) => listAnnotationSets(ctx.workspaceUser.id)),
    create: workspaceProcedure.input(annotationSetSchema).mutation(async ({ ctx, input }) => ({ id: await createAnnotationSet({ userId: ctx.workspaceUser.id, ...input, labels: input.labels as AnnotationLabel[] }) })),
    update: workspaceProcedure.input(annotationSetSchema.partial().extend({ id: z.number().int().positive(), isActive: z.boolean().optional() })).mutation(async ({ ctx, input }) => { await updateAnnotationSet({ userId: ctx.workspaceUser.id, ...input, labels: input.labels as AnnotationLabel[] | undefined }); return { success: true }; }),
    remove: workspaceProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await deleteAnnotationSet(ctx.workspaceUser.id, input.id); return { success: true }; }),
  }),
  datasets: router({
    list: workspaceProcedure.query(({ ctx }) => listDatasets(ctx.workspaceUser.id)),
    uploadJob: workspaceProcedure.input(z.object({ jobId: z.number().int().positive() })).query(({ ctx, input }) => getUploadTask(ctx.workspaceUser.id, input.jobId)),
    createUploadJob: workspaceProcedure.input(z.object({ name: z.string().min(1).max(255), fileBase64: z.string().min(20), trafficClass: datasetClasses.default("unlabeled"), annotationSetId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const annotationSet = await getAnnotationSet(ctx.workspaceUser.id, input.annotationSetId); assertLabelInSet(annotationSet, input.trafficClass); const buffer = decodePcap(input.fileBase64); const stored = await storagePut(`pcaps/public/${safeName(input.name)}`, buffer, "application/vnd.tcpdump.pcap"); return createUploadTask({ userId: ctx.workspaceUser.id, fileName: input.name, storageKey: stored.key, fileSize: buffer.length, trafficClass: input.trafficClass, annotationSetId: annotationSet.id, annotationSnapshot: annotationSet }); }),
    processUploadJob: workspaceProcedure.input(z.object({ jobId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const job = await getUploadTask(ctx.workspaceUser.id, input.jobId); if (!job || job.status !== "queued") throw new Error("上传解析任务不存在或已被处理"); try { await updateUploadTask(job.id, { status: "processing", progress: 15 }); const response = await fetch(await storageGetSignedUrl(job.storageKey)); if (!response.ok) throw new Error("无法读取已上传的 PCAP 文件"); const analysis = await analyzePcapWithNfstream(Buffer.from(await response.arrayBuffer())); await updateUploadTask(job.id, { status: "processing", progress: 55 }); const annotationSet = job.annotationSnapshotJson ? JSON.parse(job.annotationSnapshotJson) as AnnotationSetSnapshot : await getAnnotationSet(ctx.workspaceUser.id, job.annotationSetId ?? undefined); const datasetId = await createDataset({ userId: ctx.workspaceUser.id, name: job.fileName, storageKey: job.storageKey, fileSize: job.fileSize, packetCount: analysis.packetCount, flowCount: analysis.flowCount, protocolDistribution: analysis.protocolDistribution, trafficClass: job.trafficClass as TrafficClass | "unlabeled", annotationSetId: annotationSet.id, annotationSnapshot: annotationSet }); await updateUploadTask(job.id, { status: "processing", progress: 75, datasetId }); await insertFlowFeatures(datasetId, analysis.flows); await updateUploadTask(job.id, { status: "completed", progress: 100, datasetId }); return { datasetId, packetCount: analysis.packetCount, flowCount: analysis.flowCount, protocolDistribution: analysis.protocolDistribution }; } catch (error) { await updateUploadTask(job.id, { status: "failed", progress: 100, errorMessage: error instanceof Error ? error.message : "PCAP 解析失败" }); throw error; } }),
    upload: workspaceProcedure.input(z.object({ name: z.string().min(1).max(255), fileBase64: z.string().min(20), trafficClass: datasetClasses.default("unlabeled"), annotationSetId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const annotationSet = await getAnnotationSet(ctx.workspaceUser.id, input.annotationSetId); assertLabelInSet(annotationSet, input.trafficClass); const buffer = decodePcap(input.fileBase64); const analysis = await analyzePcapWithNfstream(buffer); const stored = await storagePut(`pcaps/public/${safeName(input.name)}`, buffer, "application/vnd.tcpdump.pcap"); const datasetId = await createDataset({ userId: ctx.workspaceUser.id, name: input.name, storageKey: stored.key, fileSize: buffer.length, packetCount: analysis.packetCount, flowCount: analysis.flowCount, protocolDistribution: analysis.protocolDistribution, trafficClass: input.trafficClass, annotationSetId: annotationSet.id, annotationSnapshot: annotationSet }); await insertFlowFeatures(datasetId, analysis.flows); return { datasetId, packetCount: analysis.packetCount, flowCount: analysis.flowCount, protocolDistribution: analysis.protocolDistribution }; }),
    updateLabel: workspaceProcedure.input(z.object({ datasetId: z.number().int().positive(), trafficClass: datasetClasses, annotationSetId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const annotationSet = await getAnnotationSet(ctx.workspaceUser.id, input.annotationSetId); assertLabelInSet(annotationSet, input.trafficClass); await updateDatasetLabel(ctx.workspaceUser.id, input.datasetId, input.trafficClass, annotationSet); return { success: true }; }),
    remove: workspaceProcedure.input(z.object({ datasetId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await deleteDataset(ctx.workspaceUser.id, input.datasetId); return { success: true }; }),
    features: workspaceProcedure.input(z.object({ datasetId: z.number().int().positive() })).query(({ ctx, input }) => listDatasetFeatures(ctx.workspaceUser.id, input.datasetId)),
    detail: workspaceProcedure.input(z.object({ datasetId: z.number().int().positive() })).query(({ ctx, input }) => getDataset(ctx.workspaceUser.id, input.datasetId)),
  }),
  models: router({
    list: workspaceProcedure.query(({ ctx }) => listModels(ctx.workspaceUser.id)), trainingJob: workspaceProcedure.input(z.object({ jobId: z.number().int().positive() })).query(({ ctx, input }) => getTrainingJob(ctx.workspaceUser.id, input.jobId)), activate: workspaceProcedure.input(z.object({ modelId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await activateModel(ctx.workspaceUser.id, input.modelId); return { success: true }; }),
    createTrainingJob: workspaceProcedure.input(z.object({ datasetIds: z.array(z.number().int().positive()).min(3), annotationSetId: z.number().int().positive().optional(), features: z.array(featureNames).min(3), algorithm: algorithms })).mutation(async ({ ctx, input }) => { const annotationSet = await getAnnotationSet(ctx.workspaceUser.id, input.annotationSetId); const classSet = annotationSet.labels.filter(label => label.enabled).map(label => label.key) as TrafficClass[]; return createTrainingJob({ userId: ctx.workspaceUser.id, algorithm: input.algorithm as ModelAlgorithm, datasetIds: input.datasetIds, featureSet: input.features as FeatureName[], classSet, annotationSet }); }),
    train: workspaceProcedure.input(z.object({ jobId: z.number().int().positive(), datasetIds: z.array(z.number().int().positive()).min(3), annotationSetId: z.number().int().positive().optional(), features: z.array(featureNames).min(3), algorithm: algorithms })).mutation(async ({ ctx, input }) => { const job = await getTrainingJob(ctx.workspaceUser.id, input.jobId); if (!job || job.status !== "running") throw new Error("训练任务不存在或已结束"); try { const annotationSet = snapshotFromJob(job); await updateTrainingJob(job.id, { status: "running", progress: 30 }); const samples = await getTrainingSamples(ctx.workspaceUser.id, input.datasetIds); await updateTrainingJob(job.id, { status: "running", progress: 60 }); const trained = await trainModel(samples, input.features as FeatureName[], input.algorithm as ModelAlgorithm); const models = await listModels(ctx.workspaceUser.id); const versionName = `v${models.length + 1}.${new Date().toISOString().slice(0, 10).replace(/-/g, "")}`; const metrics = trained.metrics as { accuracy: number; precision: number; recall: number; f1: number }; const modelId = await createModel({ userId: ctx.workspaceUser.id, versionName, algorithm: input.algorithm as ModelAlgorithm, featureSet: input.features as FeatureName[], classSet: trained.classes, annotationSet, metrics: trained.metrics as any, payload: trained.payload, datasetIds: input.datasetIds, isActive: models.length === 0 }); await updateTrainingJob(job.id, { status: "completed", progress: 100, modelVersionId: modelId }); return { jobId: job.id, modelId, versionName, metrics, classes: trained.classes, annotationSet, trainingCount: trained.trainingCount, validationCount: trained.validationCount }; } catch (error) { await updateTrainingJob(job.id, { status: "failed", progress: 100, errorMessage: error instanceof Error ? error.message : "训练失败" }); throw error; } }),
  }),
  apiKeys: router({ list: workspaceProcedure.query(({ ctx }) => listApiKeys(ctx.workspaceUser.id)), create: workspaceProcedure.input(z.object({ name: z.string().min(2).max(80) })).mutation(({ ctx, input }) => createApiKey(ctx.workspaceUser.id, input.name)), revoke: workspaceProcedure.input(z.object({ apiKeyId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await revokeApiKey(ctx.workspaceUser.id, input.apiKeyId); return { success: true }; }) }),
  detections: router({ list: workspaceProcedure.query(({ ctx }) => listDetectionTasks(ctx.workspaceUser.id)), detail: workspaceProcedure.input(z.object({ taskId: z.number().int().positive() })).query(({ ctx, input }) => getDetectionTask(ctx.workspaceUser.id, input.taskId)), analyze: workspaceProcedure.input(z.object({ name: z.string().min(1).max(255), fileBase64: z.string().min(20), modelId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const model = await getModel(ctx.workspaceUser.id, input.modelId); if (!model) throw new Error("选择的模型不存在"); const buffer = decodePcap(input.fileBase64); const inspected = await inspectPcap(ctx.workspaceUser.id, input.name, buffer, model.id); const stored = await storagePut(`detections/public/${safeName(input.name)}`, buffer, "application/vnd.tcpdump.pcap"); const annotationSet = model.annotationSnapshotJson ? JSON.parse(model.annotationSnapshotJson) as AnnotationSetSnapshot : await getAnnotationSet(ctx.workspaceUser.id, model.annotationSetId ?? undefined); const summary = { ...inspected.summary, modelVersion: model.versionName, annotationSet }; const taskId = await createDetectionTask({ userId: ctx.workspaceUser.id, modelVersionId: model.id, annotationSet, fileName: input.name, storageKey: stored.key, totalFlows: inspected.scored.length, highRiskFlows: inspected.summary.highRiskFlows, averageRisk: inspected.summary.averageRisk, summary }); await insertDetectionFlows(taskId, inspected.scored.slice(0, 1000).map((entry, index) => ({ ...entry, detail: inspected.flows[index] }))); return { taskId, summary, topFlows: inspected.flows.slice(0, 10) }; }) }),
  history: router({
    logs: workspaceProcedure.input(z.object({ limit: z.number().int().min(1).max(500).default(200) })).query(({ ctx, input }) => listOperationLogs(ctx.workspaceUser.id, input.limit)),
    datasets: workspaceProcedure.input(historyPageInput).query(({ ctx, input }) => listDatasetHistory(ctx.workspaceUser.id, input)), models: workspaceProcedure.input(historyPageInput).query(({ ctx, input }) => listModelHistory(ctx.workspaceUser.id, input)), detections: workspaceProcedure.input(historyPageInput).query(({ ctx, input }) => listDetectionHistory(ctx.workspaceUser.id, input)), operationLogs: workspaceProcedure.input(historyPageInput).query(({ ctx, input }) => listOperationLogHistory(ctx.workspaceUser.id, input)),
    datasetExport: workspaceProcedure.input(z.object({ datasetId: z.number().int().positive() })).query(({ ctx, input }) => exportDataset(ctx.workspaceUser.id, input.datasetId)), modelExport: workspaceProcedure.input(z.object({ modelId: z.number().int().positive() })).query(({ ctx, input }) => exportModel(ctx.workspaceUser.id, input.modelId)), detectionExport: workspaceProcedure.input(z.object({ taskId: z.number().int().positive() })).query(({ ctx, input }) => getDetectionTask(ctx.workspaceUser.id, input.taskId)),
  }),
});
export type AppRouter = typeof appRouter;
